<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\College;
use App\Department;
use App\Directorate;
use App\Section;
use App\Designation;
use App\Employee;
use App\EmployeeServiceMovement;

/**
 * EmployeeDetailsSeeder
 *
 * Generated from employee_details_20260615_090402.xlsx.
 *
 * Run after the main DeeItRepairSeeder:
 *   composer dump-autoload
 *   php artisan db:seed --class=EmployeeDetailsSeeder
 *
 * Important:
 * - The uploaded Excel file does not contain phone numbers, so this seeder imports
 *   employee master records only. It does not create login users.
 * - All imported employees are mapped to the PAU college/directorate:
 *   "Directorate of Extension Education".
 * - Since the Excel file does not contain individual department/KVK values, this seeder
 *   maps employees to department: "Directorate of Extension Education" under
 *   college/directorate: "Directorate of Extension Education". If this department
 *   does not exist, it will be created automatically.
 */
class EmployeeDetailsSeeder extends Seeder
{
    public function run()
    {
        $employeeRows = json_decode(<<<'JSON'
[
  {
    "employee_code": "11086",
    "salutation": "Dr.",
    "full_name": "Tarsem Singh Dhillon",
    "first_name": "Tarsem",
    "middle_name": "Singh",
    "last_name": "Dhillon",
    "designation": "Additional Directors of Extension Education",
    "designation_cadre": "Scientific",
    "gpf_no": "5331",
    "nps_no": null,
    "pan_no": "AAMPD0086F",
    "aadhaar_no": "721872523365",
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1992-12-21",
    "manual_increment_date": null,
    "manual_retirement_date": "2026-09-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1086 | Listing Employee Code / Active: T-11086 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5331"
  },
  {
    "employee_code": "11820",
    "salutation": "Dr.",
    "full_name": "M S BHULLAR",
    "first_name": "M",
    "middle_name": "S",
    "last_name": "BHULLAR",
    "designation": "Director of Extension Education",
    "designation_cadre": "Scientific",
    "gpf_no": "5443",
    "nps_no": null,
    "pan_no": "ABXPB2489E",
    "aadhaar_no": "378420038725",
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2023-12-15",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1821 | Listing Employee Code / Active: T-11820 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5443"
  },
  {
    "employee_code": "11987",
    "salutation": "Mr.",
    "full_name": "PRABJODH SINGH SANDHU",
    "first_name": "PRABJODH",
    "middle_name": "SINGH",
    "last_name": "SANDHU",
    "designation": "Additional Directors of Extension Education",
    "designation_cadre": "Scientific",
    "gpf_no": "5843",
    "nps_no": null,
    "pan_no": "ACHPS4156N",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1969-05-05",
    "date_of_joining": "1996-02-15",
    "manual_increment_date": "2025-07-01",
    "manual_retirement_date": "2029-05-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1988 | Listing Employee Code / Active: T-11987 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5843"
  },
  {
    "employee_code": "12298",
    "salutation": "Dr.",
    "full_name": "RITU RAJ",
    "first_name": "RITU",
    "middle_name": null,
    "last_name": "RAJ",
    "designation": "Extension Scientist",
    "designation_cadre": "Scientific",
    "gpf_no": null,
    "nps_no": "13646",
    "pan_no": "BEEPR5190D",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2017-12-01",
    "manual_increment_date": "2023-07-01",
    "manual_retirement_date": "2048-10-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2344 | Listing Employee Code / Active: T-12298 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13646"
  },
  {
    "employee_code": "11155",
    "salutation": "Mr.",
    "full_name": "Sohan Singh",
    "first_name": "Sohan",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Personal Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": "5113",
    "nps_no": null,
    "pan_no": "ADVPS8860Q",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1991-08-14",
    "manual_increment_date": null,
    "manual_retirement_date": "2029-03-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1155 | Listing Employee Code / Active: NT-11155 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5113"
  },
  {
    "employee_code": "11156",
    "salutation": "Mr.",
    "full_name": "Gurpreet Singh",
    "first_name": "Gurpreet",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12761",
    "pan_no": "AYVPS5019E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2006-03-30",
    "manual_increment_date": null,
    "manual_retirement_date": "2039-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1156 | Listing Employee Code / Active: NT-11156 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12761"
  },
  {
    "employee_code": "11158",
    "salutation": "Ms.",
    "full_name": "Daljit Kaur",
    "first_name": "Daljit",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": "5884",
    "nps_no": null,
    "pan_no": "AGXPK1525H",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1996-03-18",
    "manual_increment_date": null,
    "manual_retirement_date": "2032-03-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1158 | Listing Employee Code / Active: NT-11158 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5884"
  },
  {
    "employee_code": "11159",
    "salutation": "Ms.",
    "full_name": "Balwinder Kaur",
    "first_name": "Balwinder",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": "12418",
    "nps_no": null,
    "pan_no": "BFWPK2296C",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2002-04-24",
    "manual_increment_date": null,
    "manual_retirement_date": "2036-07-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1159 | Listing Employee Code / Active: NT-11159 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12418"
  },
  {
    "employee_code": "11160",
    "salutation": "Mr.",
    "full_name": "Khushwinder Singh",
    "first_name": "Khushwinder",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Senior Scale Stenographer",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13917",
    "pan_no": "MUEPS3806E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1996-09-13",
    "date_of_joining": "2020-08-10",
    "manual_increment_date": null,
    "manual_retirement_date": "2056-09-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1160 | Listing Employee Code / Active: NT-11160 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13917"
  },
  {
    "employee_code": "11161",
    "salutation": "Mr.",
    "full_name": "Vinod Kumar",
    "first_name": "Vinod",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Jeep Driver",
    "designation_cadre": "Administrative",
    "gpf_no": "12089",
    "nps_no": null,
    "pan_no": "BCAPK6723K",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1998-01-16",
    "manual_increment_date": null,
    "manual_retirement_date": "2033-01-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1161 | Listing Employee Code / Active: NT-11161 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12089"
  },
  {
    "employee_code": "11164",
    "salutation": "Mr.",
    "full_name": "Sham Prasad",
    "first_name": "Sham",
    "middle_name": null,
    "last_name": "Prasad",
    "designation": "Cook-cum-Attendant",
    "designation_cadre": "Administrative",
    "gpf_no": "5764",
    "nps_no": null,
    "pan_no": "APHPP3825J",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1995-11-13",
    "manual_increment_date": null,
    "manual_retirement_date": "2031-01-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1164 | Listing Employee Code / Active: NT-11164 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5764"
  },
  {
    "employee_code": "11165",
    "salutation": "Mr.",
    "full_name": "Sanjay Kumar",
    "first_name": "Sanjay",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Messenger",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12912",
    "pan_no": "BEHPK8624N",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2008-04-17",
    "manual_increment_date": null,
    "manual_retirement_date": "2036-09-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1165 | Listing Employee Code / Active: NT-11165 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12912"
  },
  {
    "employee_code": "11166",
    "salutation": "Mr.",
    "full_name": "Ram Kumar",
    "first_name": "Ram",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Chowkidar",
    "designation_cadre": "Administrative",
    "gpf_no": "12056",
    "nps_no": null,
    "pan_no": "AOOPK3752R",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1996-12-23",
    "manual_increment_date": null,
    "manual_retirement_date": "2027-01-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1166 | Listing Employee Code / Active: NT-11166 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12056"
  },
  {
    "employee_code": "11187",
    "salutation": "Mr.",
    "full_name": "Madan Lal",
    "first_name": "Madan",
    "middle_name": null,
    "last_name": "Lal",
    "designation": "Clerk",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13021",
    "pan_no": "AGCPL6684K",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2009-10-26",
    "manual_increment_date": null,
    "manual_retirement_date": "2045-03-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1187 | Listing Employee Code / Active: NT-11187 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13021"
  },
  {
    "employee_code": "11197",
    "salutation": "Mr.",
    "full_name": "Dashmesh Singh",
    "first_name": "Dashmesh",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13868",
    "pan_no": "FRVPS3965M",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2020-01-15",
    "manual_increment_date": null,
    "manual_retirement_date": "2055-11-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1197 | Listing Employee Code / Active: NT-11197 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13868"
  },
  {
    "employee_code": "11210",
    "salutation": "Ms.",
    "full_name": "Dawinder Kaur",
    "first_name": "Dawinder",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Lab Attendant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13789",
    "pan_no": "DDDPK9108L",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1980-04-02",
    "date_of_joining": "2019-02-18",
    "manual_increment_date": null,
    "manual_retirement_date": "2040-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1210 | Listing Employee Code / Active: NT-11210 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13789"
  },
  {
    "employee_code": "12810",
    "salutation": "Mr.",
    "full_name": "Shri Chand",
    "first_name": "Shri",
    "middle_name": null,
    "last_name": "Chand",
    "designation": "Farm Worker",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12705",
    "pan_no": "AMBPC8463A",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2005-10-13",
    "manual_increment_date": "2024-03-01",
    "manual_retirement_date": "2044-11-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2955 | Listing Employee Code / Active: NT-12810 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12705"
  },
  {
    "employee_code": "13292",
    "salutation": "Mrs.",
    "full_name": "Aarti Rani",
    "first_name": "Aarti",
    "middle_name": null,
    "last_name": "Rani",
    "designation": "Steno Typist",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "14080",
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2024-12-09",
    "manual_increment_date": null,
    "manual_retirement_date": "2053-07-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 3573 | Listing Employee Code / Active: NT-13292 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 14080"
  },
  {
    "employee_code": "11152",
    "salutation": "Dr.",
    "full_name": "Gurjinder Pal Singh",
    "first_name": "Gurjinder",
    "middle_name": "Pal",
    "last_name": "Singh",
    "designation": "Additional Directors of Extension Education",
    "designation_cadre": "Scientific",
    "gpf_no": "5305",
    "nps_no": null,
    "pan_no": "ADCPS3114N",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1966-08-28",
    "date_of_joining": "1992-04-03",
    "manual_increment_date": null,
    "manual_retirement_date": "2026-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1152 | Listing Employee Code / Active: T-11152 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5305"
  },
  {
    "employee_code": "11191",
    "salutation": "Dr.",
    "full_name": "Madhu Shelly",
    "first_name": "Madhu",
    "middle_name": null,
    "last_name": "Shelly",
    "designation": "Extension Scientist",
    "designation_cadre": "Scientific",
    "gpf_no": null,
    "nps_no": "13215",
    "pan_no": "BVUPS7818G",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2010-12-29",
    "manual_increment_date": null,
    "manual_retirement_date": "2039-11-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1191 | Listing Employee Code / Active: T-11191 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13215"
  },
  {
    "employee_code": "10207",
    "salutation": "Mr.",
    "full_name": "Arshpreet Singh",
    "first_name": "Arshpreet",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Steno Typist",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13907",
    "pan_no": "NDFPS0004F",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1997-12-27",
    "date_of_joining": "2020-07-27",
    "manual_increment_date": null,
    "manual_retirement_date": "2057-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 207 | Listing Employee Code / Active: NT-10207 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13907 | PRAN No: 110195012044"
  },
  {
    "employee_code": "10409",
    "salutation": "Mr.",
    "full_name": "Munish Chopra",
    "first_name": "Munish",
    "middle_name": null,
    "last_name": "Chopra",
    "designation": "Web Designer",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13994",
    "pan_no": "BSBPC0908F",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2021-02-16",
    "manual_increment_date": null,
    "manual_retirement_date": "2049-02-28",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 409 | Listing Employee Code / Active: NT-10409 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13994"
  },
  {
    "employee_code": "10695",
    "salutation": "Mr.",
    "full_name": "Gurpreet Singh",
    "first_name": "Gurpreet",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Clerk",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13883",
    "pan_no": "KYAPS6752R",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2020-01-10",
    "manual_increment_date": null,
    "manual_retirement_date": "2053-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 695 | Listing Employee Code / Active: NT-10695 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13883 | PRAN No: 110104679507"
  },
  {
    "employee_code": "11176",
    "salutation": "Mr.",
    "full_name": "Ramneek Singh",
    "first_name": "Ramneek",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13664",
    "pan_no": "JELPS8478J",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2018-02-09",
    "manual_increment_date": null,
    "manual_retirement_date": "2054-08-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1176 | Listing Employee Code / Active: NT-11176 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13664"
  },
  {
    "employee_code": "11192",
    "salutation": "Mr.",
    "full_name": "Harpreet Singh",
    "first_name": "Harpreet",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Personal Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": "5100",
    "nps_no": null,
    "pan_no": "AOYPS1871F",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1991-08-14",
    "manual_increment_date": null,
    "manual_retirement_date": "2029-09-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1192 | Listing Employee Code / Active: NT-11192 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5100"
  },
  {
    "employee_code": "11195",
    "salutation": "Ms.",
    "full_name": "Rekha",
    "first_name": "Rekha",
    "middle_name": null,
    "last_name": null,
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12740",
    "pan_no": "AJQPR8014G",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2006-03-20",
    "manual_increment_date": null,
    "manual_retirement_date": "2043-05-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1195 | Listing Employee Code / Active: NT-11195 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12740"
  },
  {
    "employee_code": "11198",
    "salutation": "Mr.",
    "full_name": "Charanjit Singh",
    "first_name": "Charanjit",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Clerk",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13791",
    "pan_no": "EQDPS3712L",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2018-11-16",
    "manual_increment_date": null,
    "manual_retirement_date": "2049-02-28",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1198 | Listing Employee Code / Active: NT-11198 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13791"
  },
  {
    "employee_code": "11199",
    "salutation": "Mr.",
    "full_name": "Rajat Kumar",
    "first_name": "Rajat",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Programmer",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13770",
    "pan_no": "BJQPS1472N",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2018-12-20",
    "manual_increment_date": null,
    "manual_retirement_date": "2043-11-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1199 | Listing Employee Code / Active: NT-11199 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13770"
  },
  {
    "employee_code": "11201",
    "salutation": "Mr.",
    "full_name": "Kulwinder Singh",
    "first_name": "Kulwinder",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Truck Driver",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13402",
    "pan_no": "BHVPS3187D",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2013-12-02",
    "manual_increment_date": null,
    "manual_retirement_date": "2035-02-28",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1201 | Listing Employee Code / Active: NT-11201 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13402"
  },
  {
    "employee_code": "11202",
    "salutation": "Mr.",
    "full_name": "Jagdish Singh",
    "first_name": "Jagdish",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Jeep Driver",
    "designation_cadre": "Administrative",
    "gpf_no": "5948",
    "nps_no": null,
    "pan_no": "ABPPS6241R",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1996-09-28",
    "manual_increment_date": null,
    "manual_retirement_date": "2030-02-28",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1202 | Listing Employee Code / Active: NT-11202 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5948"
  },
  {
    "employee_code": "11205",
    "salutation": "Mr.",
    "full_name": "Parminder Singh Chalag",
    "first_name": "Parminder",
    "middle_name": "Singh",
    "last_name": "Chalag",
    "designation": "Jeep Driver",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13699",
    "pan_no": "CNQPS1385H",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2018-05-07",
    "manual_increment_date": null,
    "manual_retirement_date": "2044-08-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1205 | Listing Employee Code / Active: NT-11205 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13699"
  },
  {
    "employee_code": "11208",
    "salutation": "Mr.",
    "full_name": "Dhruv Raj",
    "first_name": "Dhruv",
    "middle_name": null,
    "last_name": "Raj",
    "designation": "Messenger",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13020",
    "pan_no": "APKPR8678E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2009-10-19",
    "manual_increment_date": null,
    "manual_retirement_date": "2041-03-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1208 | Listing Employee Code / Active: NT-11208 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13020"
  },
  {
    "employee_code": "11209",
    "salutation": "Ms.",
    "full_name": "Manjit Kaur",
    "first_name": "Manjit",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Messenger",
    "designation_cadre": "Administrative",
    "gpf_no": "12408",
    "nps_no": null,
    "pan_no": "BCAPK5491A",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2002-04-22",
    "manual_increment_date": null,
    "manual_retirement_date": "2029-03-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1209 | Listing Employee Code / Active: NT-11209 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12408"
  },
  {
    "employee_code": "11215",
    "salutation": "Mr.",
    "full_name": "Satnam Singh",
    "first_name": "Satnam",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Farm Worker",
    "designation_cadre": "Administrative",
    "gpf_no": "5385",
    "nps_no": null,
    "pan_no": "CSSPS4982B",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1993-03-29",
    "manual_increment_date": null,
    "manual_retirement_date": "2034-02-28",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1215 | Listing Employee Code / Active: NT-11215 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5385"
  },
  {
    "employee_code": "11217",
    "salutation": "Mr.",
    "full_name": "Baljinder Kaur",
    "first_name": "Baljinder",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Messenger",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12598",
    "pan_no": "BITPK7290J",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2004-08-26",
    "manual_increment_date": null,
    "manual_retirement_date": "2031-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1217 | Listing Employee Code / Active: NT-11217 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12598"
  },
  {
    "employee_code": "11219",
    "salutation": "Mr.",
    "full_name": "Darshan Singh",
    "first_name": "Darshan",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Messenger",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13634",
    "pan_no": "HLRPS0450P",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2017-01-30",
    "manual_increment_date": null,
    "manual_retirement_date": "2057-09-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1219 | Listing Employee Code / Active: NT-11219 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13634"
  },
  {
    "employee_code": "11244",
    "salutation": "Mr.",
    "full_name": "Gurtej Singh",
    "first_name": "Gurtej",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Driver",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13382",
    "pan_no": "BZUPS0226C",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1976-01-05",
    "date_of_joining": "2013-11-27",
    "manual_increment_date": "2023-11-01",
    "manual_retirement_date": "2036-01-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1244 | Listing Employee Code / Active: NT-11244 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13382"
  },
  {
    "employee_code": "11395",
    "salutation": "Mr.",
    "full_name": "Laxmi Narayan",
    "first_name": "Laxmi",
    "middle_name": null,
    "last_name": "Narayan",
    "designation": "Clerk",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "14046",
    "pan_no": "CNUPN8095D",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2021-06-07",
    "manual_increment_date": null,
    "manual_retirement_date": "2053-10-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1395 | Listing Employee Code / Active: NT-11395 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 14046 | PRAN No: 110126562786 | Probation Completion: 2024-06-06"
  },
  {
    "employee_code": "12424",
    "salutation": "Mrs.",
    "full_name": "POOJA RANI",
    "first_name": "POOJA",
    "middle_name": null,
    "last_name": "RANI",
    "designation": "Clerk",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "20000",
    "pan_no": "CMLPR028OE",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2023-09-28",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2508 | Listing Employee Code / Active: NT-12424 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 20000 | Probation Completion: 2026-09-27"
  },
  {
    "employee_code": "12726",
    "salutation": "Mrs.",
    "full_name": "KHUSHPREET KAUR",
    "first_name": "KHUSHPREET",
    "middle_name": null,
    "last_name": "KAUR",
    "designation": "Clerk",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "14132",
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2023-09-22",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2858 | Listing Employee Code / Active: NT-12726 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 14132"
  },
  {
    "employee_code": "13904",
    "salutation": "Mr.",
    "full_name": "Gurprit Singh",
    "first_name": "Gurprit",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Beldar",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "14361",
    "pan_no": "IINPS6175K",
    "aadhaar_no": "312235610766",
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2025-05-28",
    "manual_increment_date": null,
    "manual_retirement_date": "2047-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4319 | Listing Employee Code / Active: NT-13904 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 14361"
  },
  {
    "employee_code": "12141",
    "salutation": "Mr.",
    "full_name": "NARESH KUMAR",
    "first_name": "NARESH",
    "middle_name": null,
    "last_name": "KUMAR",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": "CSJPK2022B",
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2018-01-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2161 | Listing Employee Code / Active: C-12141 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF: 101118278705"
  },
  {
    "employee_code": "12142",
    "salutation": "Mr.",
    "full_name": "JASWINDER SINGH",
    "first_name": "JASWINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": "GVQPS2850P",
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2018-01-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2162 | Listing Employee Code / Active: C-12142 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF: 101246174763"
  },
  {
    "employee_code": "12144",
    "salutation": "Mr.",
    "full_name": "MANINDERPAL SINGH",
    "first_name": "MANINDERPAL",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": "MALPS3838R",
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2018-01-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2164 | Listing Employee Code / Active: C-12144 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF: 101226013208"
  },
  {
    "employee_code": "12145",
    "salutation": "Mr.",
    "full_name": "GURINDERJEET SINGH",
    "first_name": "GURINDERJEET",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": "KTIPS5118C",
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2017-03-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2165 | Listing Employee Code / Active: C-12145 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF: 101117621984"
  },
  {
    "employee_code": "12146",
    "salutation": "Mr.",
    "full_name": "AMRITPAL SINGH",
    "first_name": "AMRITPAL",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": "KERPS5211E",
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2018-01-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2166 | Listing Employee Code / Active: C-12146 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF: 101118416940"
  },
  {
    "employee_code": "14259",
    "salutation": "Mr.",
    "full_name": "PARVINDER KUMAR",
    "first_name": "PARVINDER",
    "middle_name": null,
    "last_name": "KUMAR",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2017-07-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4692 | Listing Employee Code / Active: C-14259 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14260",
    "salutation": "Mr.",
    "full_name": "GULJAR SINGH",
    "first_name": "GULJAR",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2020-07-02",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4693 | Listing Employee Code / Active: C-14260 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14262",
    "salutation": "Mr.",
    "full_name": "SUNIL SHARMA",
    "first_name": "SUNIL",
    "middle_name": null,
    "last_name": "SHARMA",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2021-10-14",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4695 | Listing Employee Code / Active: C-14262 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14263",
    "salutation": "Mr.",
    "full_name": "BALWINDER SINGH",
    "first_name": "BALWINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2021-11-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4696 | Listing Employee Code / Active: C-14263 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14264",
    "salutation": "Mr.",
    "full_name": "MANJINDER SINGH",
    "first_name": "MANJINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2021-11-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4697 | Listing Employee Code / Active: C-14264 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14266",
    "salutation": "Mr.",
    "full_name": "PARAMDEEP SINGH",
    "first_name": "PARAMDEEP",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2021-11-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4699 | Listing Employee Code / Active: C-14266 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14267",
    "salutation": "Mr.",
    "full_name": "BALA LAKHINDER",
    "first_name": "BALA",
    "middle_name": null,
    "last_name": "LAKHINDER",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-03-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4700 | Listing Employee Code / Active: C-14267 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14269",
    "salutation": "Mr.",
    "full_name": "SUKHCHAIN SINGH",
    "first_name": "SUKHCHAIN",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2024-08-14",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4702 | Listing Employee Code / Active: C-14269 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14270",
    "salutation": "Mr.",
    "full_name": "NIRMAL SINGH",
    "first_name": "NIRMAL",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2024-12-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4703 | Listing Employee Code / Active: C-14270 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "11167",
    "salutation": "Dr.",
    "full_name": "Rupinder Kaur",
    "first_name": "Rupinder",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Associate Director (Skill Development)",
    "designation_cadre": "Scientific",
    "gpf_no": "5893",
    "nps_no": null,
    "pan_no": "AERPK9652F",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1995-05-05",
    "manual_increment_date": null,
    "manual_retirement_date": "2029-01-09",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1167 | Listing Employee Code / Active: T-11167 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5893"
  },
  {
    "employee_code": "11169",
    "salutation": "Dr.",
    "full_name": "Kulvir Kaur",
    "first_name": "Kulvir",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Extension Scientist (Fruits)",
    "designation_cadre": "Scientific",
    "gpf_no": "5858",
    "nps_no": null,
    "pan_no": "AERPK9651G",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1995-12-22",
    "manual_increment_date": null,
    "manual_retirement_date": "2030-08-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1169 | Listing Employee Code / Active: T-11169 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5858"
  },
  {
    "employee_code": "12653",
    "salutation": "Dr.",
    "full_name": "Gurpreet Singh Makkar",
    "first_name": "Gurpreet",
    "middle_name": "Singh",
    "last_name": "Makkar",
    "designation": "Senior Extension Scientist",
    "designation_cadre": "Scientific",
    "gpf_no": null,
    "nps_no": "12831",
    "pan_no": "AKLPM1856F",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2006-08-14",
    "manual_increment_date": "2024-07-01",
    "manual_retirement_date": "2035-09-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2769 | Listing Employee Code / Active: T-12653 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12831"
  },
  {
    "employee_code": "12811",
    "salutation": "Dr.",
    "full_name": "Amit Salaria",
    "first_name": "Amit",
    "middle_name": null,
    "last_name": "Salaria",
    "designation": "Extension Scientist (Agronomy)",
    "designation_cadre": "Scientific",
    "gpf_no": null,
    "nps_no": "12798",
    "pan_no": "AYIPS7731E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2006-05-04",
    "manual_increment_date": "2024-07-01",
    "manual_retirement_date": "2035-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2957 | Listing Employee Code / Active: T-12811 Active | Listing Category: Teaching | Employee Category: Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12798"
  },
  {
    "employee_code": "10131",
    "salutation": "Mr.",
    "full_name": "Rajinder Kumar",
    "first_name": "Rajinder",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": "12071",
    "nps_no": null,
    "pan_no": "ALGPD6546H",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1972-11-02",
    "date_of_joining": "1997-03-26",
    "manual_increment_date": null,
    "manual_retirement_date": "2032-11-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 131 | Listing Employee Code / Active: NT-10131 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12071"
  },
  {
    "employee_code": "10627",
    "salutation": "Mr.",
    "full_name": "Husan Kumar",
    "first_name": "Husan",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Car Supervisor",
    "designation_cadre": "Administrative",
    "gpf_no": "12195",
    "nps_no": null,
    "pan_no": "ARLPK8083D",
    "aadhaar_no": "368339074264",
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2023-10-01",
    "manual_increment_date": "2023-12-01",
    "manual_retirement_date": "2026-07-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 627 | Listing Employee Code / Active: NT-10627 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12195"
  },
  {
    "employee_code": "11163",
    "salutation": "Mr.",
    "full_name": "Harish Ram",
    "first_name": "Harish",
    "middle_name": null,
    "last_name": "Ram",
    "designation": "Steward",
    "designation_cadre": "Administrative",
    "gpf_no": "5676",
    "nps_no": null,
    "pan_no": "AGIPR9003N",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1974-08-01",
    "date_of_joining": "1994-05-17",
    "manual_increment_date": null,
    "manual_retirement_date": "2034-07-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1163 | Listing Employee Code / Active: NT-11163 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5676"
  },
  {
    "employee_code": "11171",
    "salutation": "Ms.",
    "full_name": "Baljit Kaur",
    "first_name": "Baljit",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Senior Scale Stenographer",
    "designation_cadre": "Administrative",
    "gpf_no": "5551",
    "nps_no": null,
    "pan_no": "ACJPK8987B",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1994-02-17",
    "manual_increment_date": null,
    "manual_retirement_date": "2030-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1171 | Listing Employee Code / Active: NT-11171 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5551"
  },
  {
    "employee_code": "11177",
    "salutation": "Ms.",
    "full_name": "Kanwaljit Kaur",
    "first_name": "Kanwaljit",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Extension Demonstrator",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12842",
    "pan_no": "AQHPK0587F",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2007-01-29",
    "manual_increment_date": null,
    "manual_retirement_date": "2035-07-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1177 | Listing Employee Code / Active: NT-11177 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12842"
  },
  {
    "employee_code": "11179",
    "salutation": "Mr.",
    "full_name": "Rachhpal Singh Grewal",
    "first_name": "Rachhpal",
    "middle_name": "Singh",
    "last_name": "Grewal",
    "designation": "Car Supervisor",
    "designation_cadre": "Administrative",
    "gpf_no": "11689",
    "nps_no": null,
    "pan_no": "AFRPS3777A",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1990-10-17",
    "manual_increment_date": null,
    "manual_retirement_date": "2026-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1179 | Listing Employee Code / Active: NT-11179 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 11689"
  },
  {
    "employee_code": "11181",
    "salutation": "Mr.",
    "full_name": "Lalit Kumar",
    "first_name": "Lalit",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Cook",
    "designation_cadre": "Administrative",
    "gpf_no": "5366",
    "nps_no": null,
    "pan_no": "BCAPK6738A",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1993-04-28",
    "manual_increment_date": null,
    "manual_retirement_date": "2039-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1181 | Listing Employee Code / Active: NT-11181 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5366"
  },
  {
    "employee_code": "11183",
    "salutation": "Mr.",
    "full_name": "Satwinder Singh",
    "first_name": "Satwinder",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Chowkidar",
    "designation_cadre": "Administrative",
    "gpf_no": "5308",
    "nps_no": null,
    "pan_no": "BXTPS4962E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1992-02-13",
    "manual_increment_date": null,
    "manual_retirement_date": "2031-03-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1183 | Listing Employee Code / Active: NT-11183 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5308"
  },
  {
    "employee_code": "11184",
    "salutation": "Mr.",
    "full_name": "Raj Kumar",
    "first_name": "Raj",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Sweeper",
    "designation_cadre": "Administrative",
    "gpf_no": "12419",
    "nps_no": null,
    "pan_no": "BECPK9427E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2002-04-06",
    "manual_increment_date": null,
    "manual_retirement_date": "2030-02-28",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1184 | Listing Employee Code / Active: NT-11184 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 12419"
  },
  {
    "employee_code": "11185",
    "salutation": "Mr.",
    "full_name": "Atul Kumar",
    "first_name": "Atul",
    "middle_name": null,
    "last_name": "Kumar",
    "designation": "Messenger",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13036",
    "pan_no": "BZMPK6382B",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2009-10-19",
    "manual_increment_date": null,
    "manual_retirement_date": "2045-08-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1185 | Listing Employee Code / Active: NT-11185 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13036"
  },
  {
    "employee_code": "11190",
    "salutation": "Mr.",
    "full_name": "Sukhdev Singh",
    "first_name": "Sukhdev",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Farm Worker",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13429",
    "pan_no": "FULPS5130K",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2014-07-22",
    "manual_increment_date": null,
    "manual_retirement_date": "2049-11-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1190 | Listing Employee Code / Active: NT-11190 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13429"
  },
  {
    "employee_code": "11194",
    "salutation": "Mr.",
    "full_name": "Rishi Kapoor",
    "first_name": "Rishi",
    "middle_name": null,
    "last_name": "Kapoor",
    "designation": "Superintendent",
    "designation_cadre": "Administrative",
    "gpf_no": "5460",
    "nps_no": null,
    "pan_no": "AXHPK7111J",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1974-12-26",
    "date_of_joining": "1993-07-28",
    "manual_increment_date": null,
    "manual_retirement_date": "2034-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1194 | Listing Employee Code / Active: NT-11194 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: GPF: 5460"
  },
  {
    "employee_code": "11666",
    "salutation": "Mr.",
    "full_name": "Deepak Malhotra",
    "first_name": "Deepak",
    "middle_name": null,
    "last_name": "Malhotra",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "12995",
    "pan_no": "BMTPM2435B",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2009-09-10",
    "manual_increment_date": null,
    "manual_retirement_date": "2037-10-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 1666 | Listing Employee Code / Active: NT-11666 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 12995"
  },
  {
    "employee_code": "12118",
    "salutation": "Mr.",
    "full_name": "Sanjeev Verma",
    "first_name": "Sanjeev",
    "middle_name": null,
    "last_name": "Verma",
    "designation": "Senior Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": "13536",
    "pan_no": "AHWPV3127E",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2015-12-07",
    "manual_increment_date": null,
    "manual_retirement_date": "2042-10-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 2135 | Listing Employee Code / Active: NT-12118 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS: 13536"
  },
  {
    "employee_code": "13898",
    "salutation": "Mr.",
    "full_name": "Jagdeep Singh",
    "first_name": "Jagdeep",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Steno Typist",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": "OEKPS9721G",
    "aadhaar_no": "652982707621",
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "2025-06-23",
    "manual_increment_date": null,
    "manual_retirement_date": "2057-12-31",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4311 | Listing Employee Code / Active: NT-13898 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS:"
  },
  {
    "employee_code": "15247",
    "salutation": "Mr.",
    "full_name": "TARLOCHAN SINGH",
    "first_name": "TARLOCHAN",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Bus Cleaner",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1983-04-28",
    "date_of_joining": "2026-02-12",
    "manual_increment_date": null,
    "manual_retirement_date": "2043-04-30",
    "status": "Active",
    "remarks": "Source Employee Internal ID: 5832 | Listing Employee Code / Active: NT-15247 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Working | Listing GPF/NPS: NPS:"
  },
  {
    "employee_code": "11172",
    "salutation": "Ms.",
    "full_name": "Balbir Kaur",
    "first_name": "Balbir",
    "middle_name": null,
    "last_name": "Kaur",
    "designation": "Senior Scale Stenographer",
    "designation_cadre": "Administrative",
    "gpf_no": "11650",
    "nps_no": null,
    "pan_no": "ACJPK9223C",
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1990-08-10",
    "manual_increment_date": null,
    "manual_retirement_date": "2025-06-03",
    "status": "Retired",
    "remarks": "Source Employee Internal ID: 1172 | Listing Employee Code / Active: NT-11172 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: VRS | Listing GPF/NPS: GPF: 11650"
  },
  {
    "employee_code": "15211",
    "salutation": "Mr.",
    "full_name": "Ramesh Chander Bassi",
    "first_name": "Ramesh",
    "middle_name": "Chander",
    "last_name": "Bassi",
    "designation": "Personal Assistant",
    "designation_cadre": "Administrative",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1949-10-21",
    "date_of_joining": "1969-12-16",
    "manual_increment_date": null,
    "manual_retirement_date": "2009-10-31",
    "status": "Retired",
    "remarks": "Source Employee Internal ID: 5781 | Listing Employee Code / Active: NT-15211 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Retired | Listing GPF/NPS: Choose Selected: 4736 | PPO Number: 3012"
  },
  {
    "employee_code": "13052",
    "salutation": "Mr.",
    "full_name": "Balwant Singh",
    "first_name": "Balwant",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Agricultural Sub Inspector",
    "designation_cadre": "Administrative",
    "gpf_no": "4536",
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": null,
    "date_of_joining": "1970-04-30",
    "manual_increment_date": null,
    "manual_retirement_date": "2007-04-30",
    "status": "Retired",
    "remarks": "Source Employee Internal ID: 3279 | Listing Employee Code / Active: NT-13052 Active | Listing Category: Non Teaching | Employee Category: Non Teaching | Employee Mode: Regular | Service Status: Retired | Listing GPF/NPS: GPF: 4536"
  },
  {
    "employee_code": "13712",
    "salutation": "Mr.",
    "full_name": "Swaran Singh",
    "first_name": "Swaran",
    "middle_name": null,
    "last_name": "Singh",
    "designation": "Beldar (Contract)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Permanent",
    "date_of_birth": "1951-03-10",
    "date_of_joining": "1990-03-30",
    "manual_increment_date": null,
    "manual_retirement_date": "2008-06-12",
    "status": "Inactive",
    "remarks": "Source Employee Internal ID: 4089 | Listing Employee Code / Active: C-13712 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Regular | Service Status: Expired | Listing GPF/NPS: GPF: | PPO Number: 2866"
  },
  {
    "employee_code": "14255",
    "salutation": "Mr.",
    "full_name": "PARMINDER SINGH",
    "first_name": "PARMINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2024-02-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4688 | Listing Employee Code / Active: C-14255 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: NA:"
  },
  {
    "employee_code": "14256",
    "salutation": "Mr.",
    "full_name": "HARJIT SINGH",
    "first_name": "HARJIT",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-10-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4689 | Listing Employee Code / Active: C-14256 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14253",
    "salutation": "Ms.",
    "full_name": "SANDEEP KAUR",
    "first_name": "SANDEEP",
    "middle_name": null,
    "last_name": "KAUR",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2025-04-21",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4686 | Listing Employee Code / Active: C-14253 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: NA:"
  },
  {
    "employee_code": "14254",
    "salutation": "Mr.",
    "full_name": "MANDEEP SAINI",
    "first_name": "MANDEEP",
    "middle_name": null,
    "last_name": "SAINI",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-11-06",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4687 | Listing Employee Code / Active: C-14254 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: NA:"
  },
  {
    "employee_code": "14257",
    "salutation": "Mr.",
    "full_name": "KARANVIR GILL",
    "first_name": "KARANVIR",
    "middle_name": null,
    "last_name": "GILL",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2019-08-24",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4690 | Listing Employee Code / Active: C-14257 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: NA:"
  },
  {
    "employee_code": "14258",
    "salutation": "Mr.",
    "full_name": "RAHUL GUPTA",
    "first_name": "RAHUL",
    "middle_name": null,
    "last_name": "GUPTA",
    "designation": "Contractual (Others)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2019-09-10",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4691 | Listing Employee Code / Active: C-14258 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: NA:"
  },
  {
    "employee_code": "14029",
    "salutation": "Mr.",
    "full_name": "INDERJIT SINGH",
    "first_name": "INDERJIT",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "General Assistant (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2020-06-23",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4457 | Listing Employee Code / Active: C-14029 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14030",
    "salutation": "Mrs.",
    "full_name": "RUPINDER KAUR",
    "first_name": "RUPINDER",
    "middle_name": null,
    "last_name": "KAUR",
    "designation": "General Assistant (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-09-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4458 | Listing Employee Code / Active: C-14030 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14031",
    "salutation": "Ms.",
    "full_name": "SUKHWINDER KAUR",
    "first_name": "SUKHWINDER",
    "middle_name": null,
    "last_name": "KAUR",
    "designation": "General Assistant (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-10-03",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4459 | Listing Employee Code / Active: C-14031 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14033",
    "salutation": "Mr.",
    "full_name": "TARLOCHAN SINGH",
    "first_name": "TARLOCHAN",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2017-03-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4461 | Listing Employee Code / Active: C-14033 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14034",
    "salutation": "Mr.",
    "full_name": "INDERJIT",
    "first_name": "INDERJIT",
    "middle_name": null,
    "last_name": null,
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2020-07-27",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4462 | Listing Employee Code / Active: C-14034 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14041",
    "salutation": "Mr.",
    "full_name": "SANJAY KUMAR",
    "first_name": "SANJAY",
    "middle_name": null,
    "last_name": "KUMAR",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2019-03-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4469 | Listing Employee Code / Active: C-14041 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14046",
    "salutation": "Mr.",
    "full_name": "TARSEM SINGH",
    "first_name": "TARSEM",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2020-08-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4474 | Listing Employee Code / Active: C-14046 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14048",
    "salutation": "Mr.",
    "full_name": "SUKHDEV SINGH",
    "first_name": "SUKHDEV",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-02-09",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4476 | Listing Employee Code / Active: C-14048 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14049",
    "salutation": "Mr.",
    "full_name": "DAVINDER SINGH",
    "first_name": "DAVINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2020-07-15",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4477 | Listing Employee Code / Active: C-14049 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14051",
    "salutation": "Mr.",
    "full_name": "PARGAT SINGH",
    "first_name": "PARGAT",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2019-09-02",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4479 | Listing Employee Code / Active: C-14051 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14052",
    "salutation": "Mr.",
    "full_name": "ANIL KUMAR",
    "first_name": "ANIL",
    "middle_name": null,
    "last_name": "KUMAR",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2022-10-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4480 | Listing Employee Code / Active: C-14052 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14053",
    "salutation": "Mr.",
    "full_name": "BALKAR SINGH",
    "first_name": "BALKAR",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Office Assistant-cum- Field Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-07-11",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4481 | Listing Employee Code / Active: C-14053 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14054",
    "salutation": "Mr.",
    "full_name": "SUNNY DEVGAN",
    "first_name": "SUNNY",
    "middle_name": null,
    "last_name": "DEVGAN",
    "designation": "Office Assistant-cum- Field Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2020-09-07",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4482 | Listing Employee Code / Active: C-14054 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14055",
    "salutation": "Mr.",
    "full_name": "HARPREET SINGH",
    "first_name": "HARPREET",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Office Assistant-cum- Field Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-08-21",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4483 | Listing Employee Code / Active: C-14055 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14056",
    "salutation": "Mr.",
    "full_name": "RAHUL JAGGI",
    "first_name": "RAHUL",
    "middle_name": null,
    "last_name": "JAGGI",
    "designation": "Jr. Field/ Lab. Helper (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2025-02-28",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4484 | Listing Employee Code / Active: C-14056 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14057",
    "salutation": "Mr.",
    "full_name": "MANJEET SINGH",
    "first_name": "MANJEET",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Assistant Security Supervisor (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2022-11-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4485 | Listing Employee Code / Active: C-14057 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14058",
    "salutation": "Mr.",
    "full_name": "RAVINDER SINGH",
    "first_name": "RAVINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2019-09-10",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4486 | Listing Employee Code / Active: C-14058 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14059",
    "salutation": "Mr.",
    "full_name": "PARWINDER SINGH",
    "first_name": "PARWINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2025-03-05",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4487 | Listing Employee Code / Active: C-14059 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14060",
    "salutation": "Mr.",
    "full_name": "RAVI KUMAR",
    "first_name": "RAVI",
    "middle_name": null,
    "last_name": "KUMAR",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-01-09",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4488 | Listing Employee Code / Active: C-14060 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14061",
    "salutation": null,
    "full_name": ". KULWINDER SINGH",
    "first_name": ".",
    "middle_name": "KULWINDER",
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-12-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4489 | Listing Employee Code / Active: C-14061 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14062",
    "salutation": "Mr.",
    "full_name": "MANJINDER SINGH",
    "first_name": "MANJINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2023-10-11",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4490 | Listing Employee Code / Active: C-14062 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14063",
    "salutation": "Mr.",
    "full_name": "TEJINDER SINGH",
    "first_name": "TEJINDER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2025-03-10",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4491 | Listing Employee Code / Active: C-14063 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14064",
    "salutation": "Mr.",
    "full_name": "GURPREET SINGH",
    "first_name": "GURPREET",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2025-03-05",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4492 | Listing Employee Code / Active: C-14064 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14065",
    "salutation": "Mr.",
    "full_name": "HARPREET SINGH",
    "first_name": "HARPREET",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2017-12-01",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4493 | Listing Employee Code / Active: C-14065 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14066",
    "salutation": "Mr.",
    "full_name": "MANVEER SINGH",
    "first_name": "MANVEER",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2024-07-03",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4494 | Listing Employee Code / Active: C-14066 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  },
  {
    "employee_code": "14067",
    "salutation": "Mr.",
    "full_name": "MANTAR SINGH",
    "first_name": "MANTAR",
    "middle_name": null,
    "last_name": "SINGH",
    "designation": "Jeep/Car Driver (Fixed)",
    "designation_cadre": "Supporting",
    "gpf_no": null,
    "nps_no": null,
    "pan_no": null,
    "aadhaar_no": null,
    "job_type": "Temporary",
    "date_of_birth": null,
    "date_of_joining": "2025-03-05",
    "manual_increment_date": null,
    "manual_retirement_date": null,
    "status": "Active",
    "remarks": "Source Employee Internal ID: 4495 | Listing Employee Code / Active: C-14067 Active | Listing Category: Contractual | Employee Category: Contractual | Employee Mode: Contractual | Service Status: Working | Listing GPF/NPS: EPF:"
  }
]
JSON
        , true);

        $designationRows = json_decode(<<<'JSON'
[
  {
    "name": "Additional Directors of Extension Education",
    "cadre": "Scientific"
  },
  {
    "name": "Agricultural Sub Inspector",
    "cadre": "Administrative"
  },
  {
    "name": "Assistant Security Supervisor (Fixed)",
    "cadre": "Supporting"
  },
  {
    "name": "Associate Director (Skill Development)",
    "cadre": "Scientific"
  },
  {
    "name": "Beldar",
    "cadre": "Administrative"
  },
  {
    "name": "Beldar (Contract)",
    "cadre": "Supporting"
  },
  {
    "name": "Bus Cleaner",
    "cadre": "Administrative"
  },
  {
    "name": "Car Supervisor",
    "cadre": "Administrative"
  },
  {
    "name": "Chowkidar",
    "cadre": "Administrative"
  },
  {
    "name": "Clerk",
    "cadre": "Administrative"
  },
  {
    "name": "Contractual (Others)",
    "cadre": "Supporting"
  },
  {
    "name": "Cook",
    "cadre": "Administrative"
  },
  {
    "name": "Cook-cum-Attendant",
    "cadre": "Administrative"
  },
  {
    "name": "Director of Extension Education",
    "cadre": "Scientific"
  },
  {
    "name": "Driver",
    "cadre": "Administrative"
  },
  {
    "name": "Extension Demonstrator",
    "cadre": "Administrative"
  },
  {
    "name": "Extension Scientist",
    "cadre": "Scientific"
  },
  {
    "name": "Extension Scientist (Agronomy)",
    "cadre": "Scientific"
  },
  {
    "name": "Extension Scientist (Fruits)",
    "cadre": "Scientific"
  },
  {
    "name": "Farm Worker",
    "cadre": "Administrative"
  },
  {
    "name": "General Assistant (Fixed)",
    "cadre": "Supporting"
  },
  {
    "name": "Jeep Driver",
    "cadre": "Administrative"
  },
  {
    "name": "Jeep/Car Driver (Fixed)",
    "cadre": "Supporting"
  },
  {
    "name": "Jr. Field/ Lab. Helper (Fixed)",
    "cadre": "Supporting"
  },
  {
    "name": "Lab Attendant",
    "cadre": "Administrative"
  },
  {
    "name": "Messenger",
    "cadre": "Administrative"
  },
  {
    "name": "Office Assistant-cum- Field Helper (Fixed)",
    "cadre": "Supporting"
  },
  {
    "name": "Personal Assistant",
    "cadre": "Administrative"
  },
  {
    "name": "Programmer",
    "cadre": "Administrative"
  },
  {
    "name": "Senior Assistant",
    "cadre": "Administrative"
  },
  {
    "name": "Senior Extension Scientist",
    "cadre": "Scientific"
  },
  {
    "name": "Senior Scale Stenographer",
    "cadre": "Administrative"
  },
  {
    "name": "Steno Typist",
    "cadre": "Administrative"
  },
  {
    "name": "Steward",
    "cadre": "Administrative"
  },
  {
    "name": "Superintendent",
    "cadre": "Administrative"
  },
  {
    "name": "Sweeper",
    "cadre": "Administrative"
  },
  {
    "name": "Truck Driver",
    "cadre": "Administrative"
  },
  {
    "name": "Web Designer",
    "cadre": "Administrative"
  }
]
JSON
        , true);

        DB::transaction(function () use ($employeeRows, $designationRows) {
            $directorate = Directorate::firstOrCreate(
                ['short_name' => 'DEE'],
                ['name' => 'Directorate of Extension Education', 'is_active' => 1]
            );

            $college = College::firstOrCreate(
                ['name' => 'Directorate of Extension Education'],
                ['created_at' => now(), 'updated_at' => now()]
            );

            // All imported employees are mapped to this department by default.
            // This keeps the data at DEE level. Later you can transfer employees
            // to Communication Centre / KVK / FASS / any other department from the system.
            $department = Department::firstOrCreate(
                [
                    'college_id' => $college->id,
                    'name' => 'Directorate of Extension Education',
                ],
                [
                    'place' => 'Ludhiana',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );

            $section = Section::firstOrCreate(
                ['directorate_id' => $directorate->id, 'name' => 'Administration'],
                ['short_name' => 'Admin', 'is_active' => 1]
            );

            foreach ($designationRows as $row) {
                $designation = Designation::firstOrCreate(
                    ['name' => $row['name']],
                    [
                        'cadre' => $row['cadre'],
                        'sort_order' => 0,
                        'is_active' => 1,
                    ]
                );

                if (!$designation->cadre && !empty($row['cadre'])) {
                    $designation->cadre = $row['cadre'];
                    $designation->save();
                }
            }

            foreach ($employeeRows as $row) {
                if (empty($row['employee_code'])) {
                    continue;
                }

                $designation = Designation::where('name', $row['designation'])->first();

                $calculatedRetirementDate = $this->calculateRetirementDate($row['date_of_birth'], 60);
                $finalRetirementDate = !empty($row['manual_retirement_date'])
                    ? $row['manual_retirement_date']
                    : $calculatedRetirementDate;

                $calculatedIncrementDate = $this->calculateIncrementDate($row['date_of_joining']);
                $finalIncrementDate = !empty($row['manual_increment_date'])
                    ? $row['manual_increment_date']
                    : $calculatedIncrementDate;

                $employee = Employee::updateOrCreate(
                    ['employee_code' => $row['employee_code']],
                    [
                        'directorate_id' => $directorate->id,
                        'college_id' => $college->id,
                        'department_id' => $department ? $department->id : null,
                        'section_id' => $section ? $section->id : null,
                        'designation_id' => $designation ? $designation->id : null,

                        'salutation' => $row['salutation'],
                        'first_name' => $row['first_name'] ?: 'Unknown',
                        'middle_name' => $row['middle_name'],
                        'last_name' => $row['last_name'],
                        'full_name' => $row['full_name'],

                        'gpf_no' => $row['gpf_no'],
                        'nps_no' => $row['nps_no'],
                        'pan_no' => $row['pan_no'],
                        'aadhaar_no' => $row['aadhaar_no'],

                        'job_type' => $row['job_type'],
                        'date_of_birth' => $row['date_of_birth'],
                        'date_of_joining' => $row['date_of_joining'],

                        'retirement_age' => 60,
                        'calculated_retirement_date' => $calculatedRetirementDate,
                        'manual_retirement_date' => $row['manual_retirement_date'],
                        'final_retirement_date' => $finalRetirementDate,

                        'calculated_increment_date' => $calculatedIncrementDate,
                        'manual_increment_date' => $row['manual_increment_date'],
                        'final_increment_date' => $finalIncrementDate,

                        'status' => $row['status'],
                        'remarks' => $row['remarks'],
                    ]
                );

                if (!empty($row['date_of_joining'])) {
                    EmployeeServiceMovement::firstOrCreate(
                        [
                            'employee_id' => $employee->id,
                            'movement_type' => 'Joining',
                            'effective_date' => $row['date_of_joining'],
                        ],
                        [
                            'to_designation_id' => $designation ? $designation->id : null,
                            'manual_to_designation' => $designation ? null : $row['designation'],
                            'remarks' => 'Imported from employee details Excel.',
                            'created_by' => null,
                        ]
                    );
                }
            }
        });
    }

    private function calculateRetirementDate($dob, $retirementAge = 60)
    {
        if (empty($dob)) {
            return null;
        }

        try {
            return Carbon::parse($dob)
                ->addYears($retirementAge)
                ->endOfMonth()
                ->toDateString();
        } catch (\Exception $e) {
            return null;
        }
    }

    private function calculateIncrementDate($baseDate)
    {
        if (empty($baseDate)) {
            return null;
        }

        try {
            $base = Carbon::parse($baseDate);
            $candidate = Carbon::create(Carbon::now()->year, $base->month, 1);

            if ($candidate->lt(Carbon::today())) {
                $candidate->addYear();
            }

            return $candidate->toDateString();
        } catch (\Exception $e) {
            return null;
        }
    }
}
